-- ════════════════════════════════════════════════════════════════════════════
-- Green Hope Falcons — the drill bank, seeded from the coach's own list
-- Run in: Supabase Dashboard → SQL Editor → New query → paste → Run
--
-- Run 0018_drills.sql first. This fills the bank with the drills, clips and
-- coaching material already collected, filed by category. A drill is skipped if
-- one with the same name is already there, so this is safe to re-run and safe
-- to run after you have started editing.
--
-- Minutes default to 10 — change them in the bank, or per block in a plan.
-- ════════════════════════════════════════════════════════════════════════════

insert into public.drills (name, category, link)
select v.name, v.category, v.link
from (values
  ('Seth Tierney''s "656" Drill', 'warmup', null),
  ('How Duke handles pre-practice for the preseason', 'warmup', null),
  ('Mike Morgan''s "9 Lines" Drill', 'warmup', null),
  ('"Swarm Drill" — high-energy warm-up', 'warmup', null),
  ('Numbers (Jim Berkman)', 'warmup', null),
  ('Two on one live ball', 'warmup', null),
  ('A fun one-handed drill', 'warmup', null),
  ('3v3 Bulldog (John Crawley, Johns Hopkins)', 'warmup', null),
  ('Consequences from competitions (Danowski)', 'warmup', null),
  ('Wall finishing with Nick Myers', 'warmup', null),
  ('Escape GBs (Ryan Wellner, Notre Dame)', 'groundballs', null),
  ('"Swarm GB" (Lars Tiffany)', 'groundballs', null),
  ('Apache ground ball drill', 'groundballs', null),
  ('Kevin Corrigan''s "Yo-Yo" drill', 'groundballs', null),
  ('The "Scrapping" 3-on-2 drill', 'groundballs', null),
  ('Musical chairs (youth GB)', 'groundballs', null),
  ('Relay ground balls — two triangles through cones to the goal', 'groundballs', null),
  ('Navy ground balls', 'groundballs', 'https://x.com/navymlax/status/1838535605287837698'),
  ('Manhattan toughness drills', 'groundballs', null),
  ('Aggressive ground ball play', 'faceoff', null),
  ('4v3 5v5 keep away', 'stickwork', null),
  ('Hard corners', 'stickwork', null),
  ('Spike drill — the Syracuse way', 'stickwork', null),
  ('"Star passing" stick handling', 'stickwork', null),
  ('CrosseTrainer — proper stick skills with colour (one-handed passing)', 'stickwork', null),
  ('3-player passing drill', 'stickwork', null),
  ('Step away drill (Ryan Moran, UMBC)', 'stickwork', null),
  ('Stick protection', 'stickwork', null),
  ('Footwork playlist', 'footwork', 'https://www.youtube.com/watch?v=NMVyVCyTFbM&list=PL85B9CAF991C624C0&index=209'),
  ('Speed, agility and explosiveness training for lacrosse', 'footwork', null),
  ('Drop step with tennis balls', 'footwork', null),
  ('Backyard defensive footwork workout', 'footwork', null),
  ('The Encyclopedia of Goalkeeping', 'goalie', null),
  ('Building a championship goalie', 'goalie', null),
  ('Fundamental skills and drills for the lacrosse goalie', 'goalie', null),
  ('John Galloway''s warm-up drills for goalies', 'goalie', null),
  ('Building a dominant goalie', 'goalie', null),
  ('Tony Seaman — Becoming a champion: the goalie', 'goalie', null),
  ('7 goalie drills to level up your game', 'goalie', null),
  ('Correct stance — innovative wall ball for goalies', 'goalie', null),
  ('Reaction and readiness drills (Remington Steele)', 'goalie', null),
  ('High School Coaching Academy — training the goalie', 'goalie', null),
  ('Dodging drill to train goalies', 'goalie', null),
  ('Progressive skill development for goalies and defensemen', 'goalie', null),
  ('PLL Chaos goalie clip', 'goalie', 'https://x.com/PLLChaos/status/1820454459563966496'),
  ('Goalie clip', 'goalie', 'https://youtu.be/Hyddf8y7rb4'),
  ('Face-offs drills & strategies — part 1', 'faceoff', null),
  ('Face-offs drills & strategies — part 2', 'faceoff', null),
  ('One-handed clamp drill (Kevin Reisman)', 'faceoff', null),
  ('"Bench press walks" face-off training', 'faceoff', null),
  ('3-layer dead or alive drill (Peter Dolan, High Point)', 'faceoff', 'https://coachesinsider.com/lacrosse/faceoff-3-layer-dead-or-alive-drill-with-peter-dolan-high-point-univ/'),
  ('Re-dodging', 'dodging', 'https://youtube.com/shorts/mNx6XdNvlt0'),
  ('Freeze the slide', 'dodging', null),
  ('Area 1v1s — goal to cut off man to a spot', 'dodging', null),
  ('Mark Millon''s scoring from X', 'dodging', null),
  ('Backhand fakes / BTB fakes', 'dodging', null),
  ('Jab hesitation, slide dodge', 'dodging', null),
  ('V-cut move', 'dodging', null),
  ('MJ move', 'dodging', null),
  ('Trip dodge', 'dodging', 'https://youtube.com/shorts/xIp-NMv2vjQ'),
  ('Double 1v1', 'dodging', 'https://x.com/jm3sports/status/1839765138229916036'),
  ('Cat and mouse — 1v1 with a picker', 'dodging', 'https://x.com/22classy/status/1844090171404452243'),
  ('Dodging space', 'dodging', 'https://www.facebook.com/share/r/1AhaQ6kkmG/'),
  ('Hitch move', 'dodging', null),
  ('Split dodge rollback', 'dodging', 'https://www.youtube.com/watch?v=2TS8w9ZxRDo&list=PL-xZK2kfoe_RNgFm5GGSOkVFx9r29ANUT&index=24'),
  ('Drift dodge', 'dodging', null),
  ('Face dodge to rollback shooting drill', 'dodging', null),
  ('Cat and mouse below GLE (attack dodging)', 'dodging', null),
  ('Exclamation point vs question mark', 'dodging', null),
  ('The "Answer" move', 'dodging', null),
  ('Rocker move (Greyson Torain)', 'dodging', null),
  ('Hitch and go (Garrett Degnon)', 'dodging', null),
  ('Hitch and roll', 'dodging', null),
  ('Change of speeds when dodging (Matt Brandau)', 'dodging', null),
  ('Turn the corner (Brian Minicus)', 'dodging', null),
  ('Chicken wing move (Tucker Dordevic)', 'dodging', null),
  ('Rollback footwork', 'dodging', null),
  ('Inside roll (Eric Spanos, Maryland)', 'dodging', null),
  ('The ''S'' dodge', 'dodging', null),
  ('Skip split', 'dodging', null),
  ('Salisbury shooting playlist', 'shooting', 'https://youtube.com/playlist?list=PLymobCBIpNxYoIQllppNPDPY3SQFXTAro'),
  ('Paul Rabil — tips for off-ball scoring', 'shooting', null),
  ('Adding deception', 'shooting', 'https://youtube.com/shorts/7cATYKFCaqw'),
  ('Andrew Fink''s "shooting hot spots"', 'shooting', null),
  ('Box shooting with slash cut and C-cut reads', 'shooting', null),
  ('Steve Lydon''s pop skills drill', 'shooting', null),
  ('Split and load — time and room shot', 'shooting', null),
  ('Step-off shot', 'shooting', null),
  ('Backhand fakes', 'shooting', 'https://youtube.com/shorts/XV6dYrBpJPU'),
  ('Roll work', 'shooting', 'https://www.facebook.com/share/r/18uuzxTmJb/'),
  ('Fade shooting', 'shooting', 'https://youtube.com/shorts/1tfh8m7ra8w'),
  ('Layup shooting', 'shooting', 'https://youtube.com/shorts/3HXwFgkbNYc'),
  ('Ben Rubeor — step-down shooting', 'shooting', null),
  ('In-season shooting workout (Deemer Class)', 'shooting', null),
  ('Post-practice shooting routine', 'shooting', null),
  ('Spin and fire (Matt Bohmer)', 'shooting', null),
  ('Screen shots', 'shooting', null),
  ('15 drills for building a successful shooting program', 'shooting', null),
  ('3 keys to deceptive shooting', 'shooting', null),
  ('Uppick back door cut', 'offense', 'https://youtube.com/shorts/eu4JynNiQeg'),
  ('Triple A picks', 'offense', 'https://youtube.com/shorts/w8RCrVpHayY'),
  ('First Class Lax offense clip', 'offense', 'https://x.com/firstclasslax_/status/1843668337013776487'),
  ('Offense clip', 'offense', 'https://youtube.com/shorts/y9gk28Qpy30'),
  ('Offense clip 2', 'offense', 'https://youtube.com/shorts/KkcWmAYV4TU'),
  ('Offense reel', 'offense', 'https://www.instagram.com/p/DBy9AWgR6r5/'),
  ('Transition rules (Yale)', 'transition', 'https://x.com/jm3sports/status/1827115811544183164'),
  ('Give and gos from the 2024 NCAA season', 'offense', null),
  ('Duke 1-3-2 shallow cut midfield dodging offense', 'offense', null),
  ('Installing the 1-4-1', 'offense', null),
  ('Attacking from behind the goal', 'offense', null),
  ('Dodge and kick', 'offense', null),
  ('Creating the short stick to be the first slide', 'offense', null),
  ('1-4-1 double mumbo to weave set play', 'offense', null),
  ('Zone offense (Dave Metzbower, UNC)', 'offense', null),
  ('Rutgers NASCAR offense', 'offense', null),
  ('Coaching attack with Ryan Boyle', 'offense', null),
  ('Boston University individual offensive drills', 'offense', null),
  ('Deemer Class'' hangup drill', 'offense', null),
  ('Teat dodge and skip', 'offense', 'https://youtube.com/shorts/W-h7FPsuCFU'),
  ('Setting up a perimeter (Jim Stagnitta)', 'offense', null),
  ('Principles-based offense', 'offense', null),
  ('The endline flip and seal play', 'offense', null),
  ('Lever passes', 'offense', null),
  ('Zone offense hack — 3v2 circle keep away', 'offense', null),
  ('Two-man game: fly by at X', 'offense', null),
  ('The give and go — film breakdown', 'offense', null),
  ('Razor picks', 'offense', null),
  ('Single invert micro-training', 'offense', null),
  ('10 principles of transition offense and defense', 'transition', null),
  ('Bulldog drill', 'offense', null),
  ('Tucker Dordevic roll back drill', 'offense', null),
  ('Spin seal', 'offense', null),
  ('Dave Cottle — 1-4-1 & 2-3-1 adjustable zone offense', 'offense', null),
  ('Dominating off ball (Xander Dickson)', 'offense', null),
  ('Refuse the razor pick', 'offense', null),
  ('Don Zimmerman — 2-2-2 "Deuces" offense', 'offense', null),
  ('Kick start your offense with the two-man game', 'offense', null),
  ('Alley dodge — curl — shoot', 'offense', null),
  ('How to beat a shutoff on man-up', 'specialoffense', null),
  ('End line heel play', 'specialoffense', null),
  ('Run the 1-4-1 zone offense', 'specialoffense', null),
  ('Pick game', 'specialoffense', 'https://youtube.com/shorts/xQIMCipiegY'),
  ('Coach Ruggeri clip', 'specialoffense', 'https://x.com/coachjruggeri/status/1850892020866277756'),
  ('Utah Archers sixes drill (Coach Bates)', 'sixes', null),
  ('Basic & advanced man-up offense', 'specialoffense', null),
  ('Virginia 1-4-1 pop play against the Syracuse zone', 'specialoffense', null),
  ('SU double rotating triangles', 'specialoffense', null),
  ('Man-up progressions & practice implementation', 'specialoffense', null),
  ('UNC 1-4-1 with a pop', 'specialoffense', null),
  ('Notre Dame''s EMO unit — film breakdown', 'specialoffense', null),
  ('Duke 2-4 look', 'specialoffense', null),
  ('Denver double seal play', 'specialoffense', null),
  ('Johns Hopkins flip play', 'specialoffense', null),
  ('Denver''s pack the paint defense', 'defense', null),
  ('Defending the 2-man game (Marist)', 'defense', null),
  ('Coaching aggressive team defense (JB Clarke)', 'defense', null),
  ('Andrew Fink''s trash can drill', 'defense', null),
  ('Creating a strong team defense (Lars Tiffany)', 'defense', null),
  ('Trailing to X for defenders', 'defense', null),
  ('Guarding picks', 'defense', null),
  ('3v3 shell drill (Brendan Dawson)', 'defense', null),
  ('Adding pressure to the pipeline defense', 'defense', null),
  ('Trail position slide drill (Cornell)', 'defense', null),
  ('Notre Dame slide and recovery vs Maryland', 'defense', null),
  ('First Class Lax defense clip', 'defense', 'https://x.com/firstclasslax_/status/1844792442786132000'),
  ('Building a high-pressure zone defense (Andrew Fink)', 'defense', null),
  ('Approaches and recoveries', 'individualdefense', null),
  ('Punt return sliding drill (Joe Amplo, Navy)', 'individualdefense', null),
  ('Defend the baseline — behind the cage', 'individualdefense', null),
  ('Top side defense (Chris Gabrielli)', 'individualdefense', null),
  ('Read steps', 'individualdefense', 'https://youtube.com/shorts/Gw3NJgvJerY'),
  ('Checks for defensemen (Shawn Nadelen, Towson)', 'individualdefense', null),
  ('1v1 backpedal progression (JT Giles-Harris)', 'individualdefense', null),
  ('Brett Makar''s stick in front drill', 'individualdefense', null),
  ('Hammer slide', 'individualdefense', null),
  ('Defending the "back blow" (Andrew Fink)', 'individualdefense', null),
  ('The back check', 'individualdefense', null),
  ('Brodie Merrill''s skills and drills', 'individualdefense', null),
  ('Defensive footwork & approaches (Travis Crane, Ohio State)', 'individualdefense', null),
  ('GLE lockup drill (Brett Makar)', 'individualdefense', null),
  ('Hedging and read steps (Jake Higgins)', 'individualdefense', null),
  ('How to approach X (Brett Makar)', 'individualdefense', null),
  ('Fixing common defensive mistakes', 'individualdefense', null),
  ('Individual skill development for LSMs', 'dmid', null),
  ('D-mid clip', 'dmid', 'https://www.youtube.com/shorts/EWlJVMjWr2k'),
  ('Shed drill', 'defense', null),
  ('DBR', 'defense', null),
  ('Across field 1v1s', 'individualdefense', null),
  ('32 Lunch pail', 'defense', null),
  ('Cylinder drill', 'defense', null),
  ('Skip survivor', 'defense', null),
  ('Syracuse shed', 'defense', null),
  ('L drill', 'defense', null),
  ('Man on handle — clear hands under pressure', 'individualdefense', null),
  ('Sticky drill — establish and maintain contact', 'individualdefense', null),
  ('Dead hands', 'individualdefense', null),
  ('NPC checks', 'individualdefense', null),
  ('Off-ball cutters', 'defense', null),
  ('Help side checks to the hands', 'defense', null),
  ('Ground ball exits from dangerous areas', 'groundballs', null),
  ('Playing ball at X — pressure and prepare for the dodge', 'individualdefense', null),
  ('2v1 build up comp', 'transition', null),
  ('Transition to 6v6', 'transition', null),
  ('Longpole rides', 'ridecrear', null),
  ('6v6 with LSM on offense', 'transition', null),
  ('Munro drill', 'transition', null),
  ('Small sided 2v1 clearing build up', 'ridecrear', null),
  ('3v2 clearing', 'ridecrear', null),
  ('4v3 clearing', 'ridecrear', null),
  ('6v6 clearing', 'ridecrear', null),
  ('Sideline clears 2v2 to 3v2', 'ridecrear', null),
  ('Two-handed riding', 'ridecrear', null),
  ('Roll pressure with a re-direct (Jim Berkman)', 'ridecrear', null),
  ('Clearing practice (Richie Meade)', 'ridecrear', null),
  ('Midfield riding drill', 'ridecrear', null),
  ('Mastering the clearing game — Duke express offense', 'ridecrear', null),
  ('Rotate correctly within a man-down defense', 'mandown', null),
  ('Circle of consistency', 'sixes', null),
  ('4v4 box', 'sixes', null),
  ('2v1 picker dodger (6v6 build up)', 'sixes', null),
  ('3v3 side game', 'sixes', null),
  ('3v3 side with feeder', 'sixes', null),
  ('4v4 behind the net', 'sixes', null),
  ('Hippo drill (Kyle Smedley)', 'sixes', null),
  ('Pairs — Hopkins pairs offense', 'sixes', null),
  ('Slip picks at GLE', 'sixes', null),
  ('Skeleton clip', 'sixes', 'https://x.com/tommariano81/status/1844452089902268786'),
  ('Skeleton clip 2', 'sixes', 'https://x.com/tommariano81/status/1845842863109669306'),
  ('"Loose"', 'sixes', 'https://x.com/terencefoy/status/1844808136730857562'),
  ('3-on-2 (Mike Pressler)', 'sixes', null),
  ('2v1 3v2 transition work (Seth Tierney)', 'transition', null),
  ('The "Scrappin''" half field team drill', 'sixes', null),
  ('All Access Syracuse Lacrosse practice', 'conditioning', null),
  ('Testing and evaluation for lacrosse players', 'conditioning', null),
  ('Conditioning clip', 'conditioning', 'https://www.facebook.com/share/r/19ZqL1cm38/'),
  ('Paul Rabil''s guide to getting fast & strong', 'strength', null),
  ('Strength training for lacrosse — 4 keys', 'strength', null),
  ('The Atomic Workout — 16 minute speed workout', 'strength', null),
  ('Powerful mental exercise for young players', 'mental', null),
  ('IQ session', 'mental', null),
  ('How to stand out at lacrosse tryouts', 'tryouts', null),
  ('Keep it classy', 'tryouts', null),
  ('Want more playing time? 3 things athletes should consider', 'tryouts', null),
  ('Techniques with John Danowski', 'planning', null),
  ('Practice organization for lacrosse (Bill Tierney)', 'planning', null),
  ('All-Access Duke Lacrosse Vol. I — 1-on-1 and team drills', 'planning', null),
  ('Addition of a teammate (Danowski)', 'planning', null),
  ('Call sheet — one word for all situations (Belichick)', 'planning', null),
  ('Leadership — Tottenham laughing gas ban', 'leadership', 'https://www.espn.com/soccer/story/_/id/40868831/tottenham-hand-yves-bissouma-ban-laughing-gas-video'),
  ('Fun reel', 'fun', 'https://www.instagram.com/reel/C-N9_khM_sV/'),
  ('Drill bank short', 'planning', 'https://youtube.com/shorts/bx3ipyyD-do'),
  ('Unnecessary roughness clip', 'planning', 'https://x.com/unnecroughness/status/1844347932319109596')
) as v(name, category, link)
where not exists (select 1 from public.drills d where d.name = v.name);
