-- ════════════════════════════════════════════════════════════════════════════
-- Green Hope Falcons — where a drill can actually be done
-- Run in: Supabase Dashboard → SQL Editor → New query → paste → Run
--
-- Six position coaches went through the bank and said, drill by drill, whether
-- a player can do it on a wall, alone, with one friend, only at practice, or
-- only by watching it. That answer is what keeps a 6v6 install or a film
-- breakdown out of a kid's homework.
--
-- Anything not named below stays 'team', which means it is never prescribed as
-- individual work. That is deliberate: guessing from a drill's name or category
-- is how a Duke install ends up in a driveway.
--
-- Safe to re-run.
-- ════════════════════════════════════════════════════════════════════════════

alter table public.drills
  add column if not exists setting text not null default 'team';

do $$
begin
  if not exists (select 1 from pg_constraint where conname = 'drills_setting_check') then
    alter table public.drills
      add constraint drills_setting_check
      check (setting in ('wall', 'solo', 'partner', 'team', 'film'));
  end if;
end $$;

create index if not exists drills_setting_idx on public.drills (setting);

update public.drills d
set setting = v.setting
from (values
  ('"Bench press walks" face-off training', 'solo'),
  ('"Star passing" stick handling', 'partner'),
  ('"Swarm GB" (Lars Tiffany)', 'team'),
  ('10 principles of transition offense and defense', 'film'),
  ('1v1 backpedal progression (JT Giles-Harris)', 'partner'),
  ('2v1 3v2 transition work (Seth Tierney)', 'team'),
  ('3 keys to deceptive shooting', 'film'),
  ('3-layer dead or alive drill', 'partner'),
  ('3-layer dead or alive drill (Peter Dolan, High Point)', 'partner'),
  ('3-player passing drill', 'partner'),
  ('32 Lunch pail', 'team'),
  ('3v2 clearing', 'team'),
  ('3v3 Bulldog (John Crawley, Johns Hopkins)', 'team'),
  ('3v3 shell drill', 'team'),
  ('3v3 shell drill (Brendan Dawson)', 'team'),
  ('4v3 5v5 keep away', 'team'),
  ('4v3 clearing', 'team'),
  ('4v4 box', 'team'),
  ('6v6 clearing', 'team'),
  ('6v6 with LSM on offense', 'team'),
  ('7 goalie drills to level up your game', 'partner'),
  ('A fun one-handed drill', 'wall'),
  ('Across field 1v1s', 'partner'),
  ('Adding deception', 'solo'),
  ('Addition of a teammate', 'film'),
  ('Addition of a teammate (Danowski)', 'film'),
  ('Andrew Fink''s "shooting hot spots"', 'film'),
  ('Andrew Fink''s trash can drill', 'solo'),
  ('Apache ground ball drill', 'partner'),
  ('Approaches and recoveries', 'solo'),
  ('Attacking from behind the goal', 'film'),
  ('Backyard defensive footwork workout', 'solo'),
  ('Ben Rubeor — step-down shooting', 'solo'),
  ('Brett Makar''s stick in front drill', 'partner'),
  ('Brodie Merrill''s skills and drills', 'film'),
  ('Building a championship goalie', 'film'),
  ('Bulldog drill', 'partner'),
  ('Call sheet — one word for all situations (Belichick)', 'film'),
  ('Cat and mouse below GLE (attack dodging)', 'partner'),
  ('Cat and mouse — 1v1 with a picker', 'team'),
  ('Change of speeds', 'solo'),
  ('Change of speeds when dodging (Matt Brandau)', 'solo'),
  ('Checks for defensemen', 'film'),
  ('Checks for defensemen (Shawn Nadelen, Towson)', 'film'),
  ('Circle of consistency', 'team'),
  ('Clearing practice (Richie Meade)', 'team'),
  ('Coaching attack with Ryan Boyle', 'film'),
  ('Conditioning clip', 'solo'),
  ('Consequences from competitions (Danowski)', 'team'),
  ('Correct stance — innovative wall ball for goalies', 'wall'),
  ('Creating a strong team defense', 'film'),
  ('Creating a strong team defense (Lars Tiffany)', 'film'),
  ('CrosseTrainer — proper stick skills with colour (one-handed passing)', 'wall'),
  ('Dead hands', 'solo'),
  ('Deemer Class'' hangup drill', 'partner'),
  ('Defend the baseline — behind the cage', 'partner'),
  ('Defending the 2-man game (Marist)', 'film'),
  ('Defensive footwork & approaches (Travis Crane, Ohio State)', 'solo'),
  ('Denver''s pack the paint defense', 'film'),
  ('Dodge and kick', 'team'),
  ('Dodging drill to train goalies', 'partner'),
  ('Dominating off ball', 'film'),
  ('Dominating off ball (Xander Dickson)', 'film'),
  ('Double 1v1', 'partner'),
  ('Drop step with tennis balls', 'solo'),
  ('Escape GBs', 'partner'),
  ('Escape GBs (Ryan Wellner, Notre Dame)', 'partner'),
  ('Face-offs drills & strategies — part 1', 'film'),
  ('Face-offs drills & strategies — part 2', 'film'),
  ('Fade shooting', 'solo'),
  ('Fixing common defensive mistakes', 'film'),
  ('Footwork playlist', 'solo'),
  ('Freeze the slide', 'team'),
  ('Fundamental skills and drills for the lacrosse goalie', 'film'),
  ('GLE lockup drill (Brett Makar)', 'partner'),
  ('Give and gos', 'film'),
  ('Give and gos from the 2024 NCAA season', 'film'),
  ('Ground ball exits from dangerous areas', 'partner'),
  ('Hammer slide', 'team'),
  ('Hard corners', 'wall'),
  ('Hedging and read steps (Jake Higgins)', 'solo'),
  ('Help side checks to the hands', 'team'),
  ('High School Coaching Academy — training the goalie', 'film'),
  ('Hippo drill (Kyle Smedley)', 'team'),
  ('Hitch and go (Garrett Degnon)', 'solo'),
  ('How to stand out at lacrosse tryouts', 'film'),
  ('IQ session', 'film'),
  ('In-season shooting workout', 'solo'),
  ('In-season shooting workout (Deemer Class)', 'solo'),
  ('Individual skill development for LSMs', 'film'),
  ('Installing the 1-4-1', 'film'),
  ('Jab hesitation, slide dodge', 'solo'),
  ('John Galloway''s warm-up drills for goalies', 'partner'),
  ('Keep it classy', 'film'),
  ('Kevin Corrigan''s "Yo-Yo" drill', 'solo'),
  ('Kick start your offense with the two-man game', 'film'),
  ('Layup shooting', 'solo'),
  ('Leadership — Tottenham laughing gas ban', 'film'),
  ('Lever passes', 'partner'),
  ('Longpole rides', 'team'),
  ('Man on handle — clear hands under pressure', 'partner'),
  ('Manhattan toughness drills', 'team'),
  ('Mark Millon''s scoring from X', 'film'),
  ('Mastering the clearing game', 'film'),
  ('Mastering the clearing game — Duke express offense', 'film'),
  ('Midfield riding drill', 'team'),
  ('Munro drill', 'team'),
  ('NPC checks', 'solo'),
  ('Navy ground balls', 'partner'),
  ('Notre Dame slide and recovery vs Maryland', 'film'),
  ('Notre Dame''s EMO unit — film breakdown', 'film'),
  ('Off-ball cutters', 'team'),
  ('One-handed clamp drill (Kevin Reisman)', 'solo'),
  ('PLL Chaos goalie clip', 'film'),
  ('Paul Rabil — tips for off-ball scoring', 'film'),
  ('Paul Rabil''s guide', 'solo'),
  ('Paul Rabil''s guide to getting fast & strong', 'solo'),
  ('Playing ball at X', 'partner'),
  ('Playing ball at X — pressure and prepare for the dodge', 'partner'),
  ('Post-practice shooting routine', 'solo'),
  ('Powerful mental exercise for young players', 'film'),
  ('Principles-based offense', 'film'),
  ('Progressive skill development for goalies and defensemen', 'partner'),
  ('Punt return sliding drill (Joe Amplo, Navy)', 'team'),
  ('Re-dodging', 'partner'),
  ('Reaction and readiness drills (Remington Steele)', 'partner'),
  ('Read steps', 'solo'),
  ('Roll pressure with a re-direct (Jim Berkman)', 'team'),
  ('Rollback footwork', 'solo'),
  ('Rotate correctly within a man-down defense', 'team'),
  ('Sideline clears 2v2 to 3v2', 'team'),
  ('Small sided 2v1 clearing build up', 'team'),
  ('Speed, agility and explosiveness', 'solo'),
  ('Speed, agility and explosiveness training for lacrosse', 'solo'),
  ('Spike drill', 'partner'),
  ('Spike drill — the Syracuse way', 'partner'),
  ('Split and load — time and room shot', 'solo'),
  ('Split dodge rollback', 'solo'),
  ('Step away drill', 'partner'),
  ('Step away drill (Ryan Moran, UMBC)', 'partner'),
  ('Step-off shot', 'solo'),
  ('Stick protection', 'solo'),
  ('Sticky drill', 'partner'),
  ('Sticky drill — establish and maintain contact', 'partner'),
  ('Strength training for lacrosse — 4 keys', 'solo'),
  ('Strength training — 4 keys', 'solo'),
  ('Teat dodge and skip', 'team'),
  ('Techniques with John Danowski', 'film'),
  ('Testing and evaluation', 'solo'),
  ('Testing and evaluation for lacrosse players', 'solo'),
  ('The "Scrappin''" half field team drill', 'team'),
  ('The "Scrapping" 3-on-2 drill', 'team'),
  ('The Atomic Workout', 'solo'),
  ('The Atomic Workout — 16 minute speed workout', 'solo'),
  ('The back check', 'partner'),
  ('The give and go — film breakdown', 'film'),
  ('Tony Seaman — Becoming a champion: the goalie', 'film'),
  ('Top side defense (Chris Gabrielli)', 'partner'),
  ('Trail position slide drill (Cornell)', 'team'),
  ('Transition rules (Yale)', 'film'),
  ('Turn the corner', 'partner'),
  ('Turn the corner (Brian Minicus)', 'partner'),
  ('Two on one live ball', 'team'),
  ('Two-handed riding', 'team'),
  ('Two-man game: fly by at X', 'team'),
  ('Unnecessary roughness clip', 'film'),
  ('Uppick back door cut', 'partner'),
  ('V-cut move', 'solo'),
  ('Wall finishing with Nick Myers', 'wall'),
  ('Want more playing time? 3 things athletes should consider', 'film'),
  ('Zone offense hack — 3v2 circle keep away', 'team')
) as v(name, setting)
where d.name = v.name and d.setting is distinct from v.setting;
